# Supabase project configuration.

project_id = "capitolio-consultores"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[functions]
  [functions.process-document]
    handler = "main"
    timeout_s = 300
